### ISSUE TITLE
Can't compile with FV_PRECISION=R8

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/FVdycoreCubed_GridComp#1]
In `fv_getUpdraftHelicity` (in FV_StateMod.F90) `uh25` is a real with width `FVPRC` (R8 for GCHP):
https://github.com/geoschem/FVdycoreCubed_GridComp/blob/2159d986cc8c677e4a97a25b4954498f6f1386d8/FV_StateMod.F90#L3554-L3568

In the dynamics core's `Run()` subroutine `uh25` is gotten with a `real(kind=r4)` called `temp2d`:

https://github.com/geoschem/FVdycoreCubed_GridComp/blob/0698dbd763b9d0bbda8db4c91c4418a591e7051d/DynCore_GridCompMod.F90#L2811

https://github.com/geoschem/FVdycoreCubed_GridComp/blob/0698dbd763b9d0bbda8db4c91c4418a591e7051d/DynCore_GridCompMod.F90#L4753-L4760

This causes a compiler error when `AdvCore_GridComp` is compiling. 

### Work around
To work around this I created a new pointer with kind `FVPRC`. Then I called `MAPL_GetPointer` and `fv_getUpdraftHelicity` with this pointer. 

Patch file: [AdvCore_GridComp-patch.txt](https://github.com/geoschem/FVdycoreCubed_GridComp/files/3566685/AdvCore_GridComp-patch.txt) (can be applied with `git apply AdvCore_GridComp-patch.txt` in the `AdvCore_GridComp` subdirectory).

**Comment by LiamBindle** [comment]
Fixed with 201f10f I believe

**Comment by lizziel** [comment]
https://github.com/geoschem/FVdycoreCubed_GridComp/commit/201f10f548ad295c0293f22a1d85fb31f252c228 fixed a separate issue that was triggered by the same call. Reopening until a fix is pushed.

**Comment by lizziel** [comment]
Now fixed with combination of https://github.com/geoschem/FVdycoreCubed_GridComp/commit/201f10f548ad295c0293f22a1d85fb31f252c228 and https://github.com/geoschem/FVdycoreCubed_GridComp/commit/99d6ef246afc7aa064a046958006ddeaff288730. This issue and a suggested fix were previously documented in GMAO issue https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/60. The update pushed is based on GMAO's work-around for GEOS CTM.
